pipelines:
  branches:
    master:
      - step:
          name: Release to prod
          image: misterio92/ci-php-node
          script:
            - composer install --no-dev
            - composer run build-assets
            - find $BITBUCKET_CLONE_DIR -name "node_modules" -exec rm -rf '{}' + # Delete node_modules folders
            - rm -rf $BITBUCKET_CLONE_DIR/.git*
            - rm -rf $BITBUCKET_CLONE_DIR/bitbucket-pipelines.yml
            - rm -rf $BITBUCKET_CLONE_DIR/composer.json
            - rm -rf $BITBUCKET_CLONE_DIR/composer.lock
            - rm -rf $BITBUCKET_CLONE_DIR/package.json
            - rm -rf $BITBUCKET_CLONE_DIR/package-lock.json
            - chmod 0775 $BITBUCKET_CLONE_DIR # Ensure file permission for main dir
            - find $BITBUCKET_CLONE_DIR -type f -exec chmod 0664 {} \; # Ensure file permission for all files
            - find $BITBUCKET_CLONE_DIR -type d -exec chmod 0775 {} \; # Ensure file permission for all dirs
            - rsync -azr --delete $BITBUCKET_CLONE_DIR/ root@ledyer.demonstrer.es:/home/ledyer15356/sites/ledyer.demonstrer.es/releases/$BITBUCKET_BUILD_NUMBER/ # rsync release
            - ssh root@ledyer.demonstrer.es "ln -sfn /home/ledyer15356/sites/ledyer.demonstrer.es/releases/$BITBUCKET_BUILD_NUMBER /home/ledyer15356/sites/ledyer.demonstrer.es/htdocs/wp-content/plugins/ledyer-checkout-for-woocommerce" # symlink new release
            - ssh root@ledyer.demonstrer.es "chown -R ledyer15356:ledyer15356 /home/ledyer15356/sites/ledyer.demonstrer.es/htdocs/wp-content/plugins/ledyer-checkout-for-woocommerce" # change plugin ownership
      - step:
          name: Test
          image: docker/compose:1.29.2
          script:
            - cd tests/e2e
            - echo LEDYER_DEV_MERCHANT_ID=\"$LEDYER_DEV_MERCHANT_ID\" >> .env
            - echo LEDYER_DEV_SHARED_SECRET=\"$LEDYER_DEV_SHARED_SECRET\" >> .env
            - echo CYPRESS_PROJECT_ID=\"$CYPRESS_PROJECT_ID\" >> .env
            - docker-compose up -d --build
            - docker-compose run --rm plugin clone $PLUGIN_REPOSITORY temp
            - chmod -R 777 .
            - docker-compose run --rm cli sh -c "mkdir -p ./wp-content/plugins/ledyer-checkout-for-woocommerce"
            - docker-compose run --rm cli sh -c "cp -R /plugin/temp/* ./wp-content/plugins/ledyer-checkout-for-woocommerce"
            - docker-compose run --rm cli sh -c "./wp-content/plugins/ledyer-checkout-for-woocommerce/tests/e2e/cli/wait-for-it.sh db:3306"
            - chmod -R 777 .
            - docker-compose run -e HOME=/tmp --rm cli sh ./wp-content/plugins/ledyer-checkout-for-woocommerce/tests/e2e/cli/wordpress.sh
            - echo "Tests for PB checkout run here"
            - docker-compose run e2e --record --key $LEDYER_CYPRESS_KEY
          services:
            - docker
          caches:
            - docker

